### PR TITLE
ext4: easy malloc/calloc/realloc/free substitution

### PR DESCRIPTION
**Pull request by mmajewicz**
Sometimes it's helpful to be able to substitute malloc/free (and family) with one easy step.
Here is my proposal to enable such a substitution.

I understand that proposed names and placing of #define's isn't perfect - it's just an idea.

### CODE REVIEW

**Comment by gkostka** [comment]
Hello Michal,

Option USE_OTHER_MALLOC should be in config header i think (with CONFIG prefix). W would like to slightly change names ot the user defined functions to user_malloc, user_free etc. This option should be disabled by default

**Comment by mmajewicz** [comment]
Hello Grzegorz,

If understood You correctly I made requested changes and pushed in second commit.

**Comment by gkostka** [comment]
Ok, looks good to me.

**Comment by gkostka** [comment]
Hello again. I've made a little allocator prefix change here:
https://github.com/gkostka/lwext4/commit/318276320cd6beafa4781aaa1d6694c60adeb18a

**Comment by mmajewicz** [comment]
I agree that "ext4_user" prefix is better.

Thank You for accepting my proposal.

**Comment by gkostka** [comment]
No problem. I'm looking forward new pull requests:)  Thanks!

**Pull request merged**
